export default function applyBuiltInErrHandler(divider, log = console.log) {
  if (typeof divider?.subscribe !== 'function') {
    throw new Error(`
      The divider maybe be not generated by createDivider() .
    `);
  }

  const logs = {};

  divider.subscribe('start', ({ type, ...rest }) => {
    type && (logs[type] = {
      ...rest
    });
  });

  divider.subscribe('end', (...args) => {
    const { type } = args[1] || {};
    type && delete logs[type];
  });

  divider?.setErrorHandler(({ error, action }) => {
    const rest = { ...logs };
    action.type && delete rest[action.type];

    log({
      error,
      occur: action,
      others: {
        ...rest
      }
    });
  });
}